# Generated by Django 6.0.2 on 2026-03-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0003_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('attendance_officer', 'Attendance Officer'), ('finance_officer', 'Finance Officer'), ('viewer', 'Viewer')], default='viewer', max_length=50),
        ),
    ]
