# Generated by Django 6.0.2 on 2026-03-03 11:47

from django.db import migrations


def create_finance_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Finance Officer')

class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.RunPython(create_finance_group),
    ]
