# Generated by Django 6.0.2 on 2026-03-03 12:06

from django.db import migrations


def migrate_departments(apps, schema_editor):
    Member = apps.get_model('church_management', 'Member')
    Department = apps.get_model('church_management', 'Department')
    
    for member in Member.objects.all():
        if member.department:
            dept, _ = Department.objects.get_or_create(name=member.department)
            member.department_link = dept
            member.save()

def reverse_migrate_departments(apps, schema_editor):
    Member = apps.get_model('church_management', 'Member')
    for member in Member.objects.all():
        if member.department_link:
            member.department = member.department_link.name
            member.save()

class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0006_department_member_department_link'),
    ]

    operations = [
        migrations.RunPython(migrate_departments, reverse_migrate_departments),
    ]
