# Generated by Django 6.0.2 on 2026-03-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0007_migrate_department_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='department',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='department_link',
            new_name='department',
        ),
    ]
