# Generated by Django 6.0.2 on 2026-03-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0009_alter_profile_role_child_childcheckin_prayerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='RCCG Emmanuel Sanctuary', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo_url', models.URLField(blank=True, default='/rccg_logo.png', max_length=500, null=True)),
                ('attendance_reminders', models.BooleanField(default=True)),
                ('new_member_alerts', models.BooleanField(default=True)),
                ('weekly_reports', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
