# Generated by Django 6.0.2 on 2026-03-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0010_churchsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsettings',
            name='logo_url',
            field=models.TextField(blank=True, default='/rccg_logo.png', null=True),
        ),
    ]
