# Generated by Django 6.0.2 on 2026-03-04 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0017_smstemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='updated_at',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='leader',
            new_name='head_of_department',
        ),
    ]
