# Generated by Django 6.0.2 on 2026-03-04 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0018_rename_department_leader_to_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='church_management.member'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='church_management.member'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('attendance_officer', 'Attendance Officer'), ('finance_officer', 'Finance Officer'), ('children_officer', 'Children Officer'), ('prayer_officer', 'Prayer Officer'), ('hod', 'HOD'), ('viewer', 'Viewer')], default='viewer', max_length=50),
        ),
    ]
