# Generated by Django 6.0.2 on 2026-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0020_budget_pledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('attendance_officer', 'Attendance Officer'), ('finance_officer', 'Finance Officer'), ('children_officer', 'Children Officer'), ('prayer_officer', 'Prayer Officer'), ('hod', 'HOD'), ('viewer', 'Viewer')], default=None, max_length=50, null=True),
        ),
    ]
