# Generated by Django 6.0.2 on 2026-03-05 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0021_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_in_requests', to='church_management.member')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_requests', to='church_management.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
