# Generated by Django 6.0.2 on 2026-03-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0022_checkinqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('welfare', 'Welfare'), ('building_fund', 'Building Fund'), ('thanksgiving', 'Thanksgiving'), ('seeds', 'Seeds'), ('donation', 'Donation'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('salary', 'Salary / Welfare'), ('projects', 'Church Projects'), ('administration', 'Administration'), ('outreach', 'Outreach / Evangelism'), ('purchase', 'Purchases / Equipment'), ('other', 'Other')], max_length=50),
        ),
    ]
