# Generated by Django 6.0.2 on 2026-03-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0023_alter_contribution_contribution_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='department',
        ),
        migrations.AddField(
            model_name='member',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='members', to='church_management.department'),
        ),
    ]
