# Generated by Django 6.0.2 on 2026-03-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0026_inventoryitem_family_member_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
