# Generated by Django 6.0.2 on 2026-03-13 13:57

from django.conf import settings
from django.db import migrations, models


def split_full_name(apps, schema_editor):
    Member = apps.get_model('church_management', 'Member')
    for member in Member.objects.all():
        full_name = getattr(member, 'full_name', '')
        if not full_name:
            continue
        names = full_name.strip().split(' ')
        if len(names) >= 2:
            member.surname = names[0]
            member.firstname = names[1]
            if len(names) > 2:
                member.other_name = ' '.join(names[2:])
        else:
            member.surname = names[0]
            member.firstname = 'TBD'
        member.save()

def reverse_split(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0027_profile_is_two_factor_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='member',
            name='unique_member_name_phone',
        ),
        migrations.AddField(
            model_name='member',
            name='church_membership',
            field=models.CharField(blank=True, choices=[('worker', 'Worker'), ('minister', 'Minister')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='department_post',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='TBD', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='ordained_as',
            field=models.CharField(blank=True, choices=[('deacon', 'Deacon'), ('deaconess', 'Deaconess'), ('full_pastor', 'Full Pastor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='other_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='surname',
            field=models.CharField(default='TBD', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='year_joined',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='year_ordination',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(split_full_name, reverse_split),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('surname', 'firstname', 'phone'), name='unique_member_fields'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='full_name',
        ),
    ]
