# Generated by Django 6.0.2 on 2026-03-13 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0028_remove_member_unique_member_name_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='spiritual_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spiritual_headed_families', to='church_management.member'),
        ),
    ]
