# Generated by Django 6.0.3 on 2026-03-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0029_add_spiritual_head_to_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_ordained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='year_joined_workforce',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
