# Generated by Django 6.0.3 on 2026-04-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0030_member_is_ordained_member_year_joined_workforce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ordained_as',
            field=models.CharField(blank=True, choices=[('deacon', 'Deacon'), ('deaconess', 'Deaconess'), ('minister', 'Minister'), ('assistant_pastor', 'Assistant Pastor'), ('full_pastor', 'Full Pastor')], max_length=20, null=True),
        ),
    ]
