# Generated by Django 6.0.3 on 2026-04-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0031_alter_member_ordained_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
