# Generated by Django 6.0.3 on 2026-04-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0032_alter_member_email_alter_member_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='service_times',
            field=models.TextField(blank=True, help_text='List your service times (e.g. Sundays 9am, 11am)', null=True),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churchsettings',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
