# Generated by Django 6.0.3 on 2026-04-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0033_churchsettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('welfare', 'Welfare'), ('building_fund', 'Building Fund'), ('thanksgiving', 'Thanksgiving'), ('seeds', 'Seeds'), ('donation', 'Donation'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateField(db_index=True),
        ),
    ]
