# Generated by Django 6.0.3 on 2026-04-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_management', '0034_alter_attendancerecord_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsettings',
            name='auto_confirm_qr_checkin',
            field=models.BooleanField(default=False),
        ),
    ]
